---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-app
  namespace: workout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-app
  template:
    metadata:
      labels:
        app: workout-app
    spec:
      containers:
        - name: workout-app
          image: ghcr.io/mortennordbye/workout:sha-e0eb06b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: BETTER_AUTH_URL
              value: "https://workout.nordbye.it"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workout-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres.workout.svc.cluster.local:5432/workout_db"
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: workout-secret
                  key: BETTER_AUTH_SECRET
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: workout-secret
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workout-secret
                  key: ADMIN_PASSWORD
            - name: ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: workout-secret
                  key: ADMIN_NAME
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: workout-app
  namespace: workout
spec:
  selector:
    app: workout-app
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
