apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: workout-secret
  namespace: workout
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: workout-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "fbae7327-2f9c-4881-91cb-b421013834f8"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: "better-auth-secret"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: "admin-email"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: "admin-password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ADMIN_NAME
      remoteRef:
        key: "admin-name"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
