import { BottomNav } from "@/components/ui/bottom-nav";
import { PageTransition } from "@/components/features/PageTransition";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { WorkoutSessionProvider } from "@/contexts/workout-session-context";
import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Prevent flash of light mode — runs before first paint */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var s=localStorage.getItem('theme');if(s==='dark'||(s===null&&window.matchMedia('(prefers-color-scheme:dark)').matches)){document.documentElement.classList.add('dark')}})()`,
          }}
        />
      </head>
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased pb-16`}
      >
        <ThemeProvider>
          <WorkoutSessionProvider>
            <PageTransition>{children}</PageTransition>
            <BottomNav />
          </WorkoutSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
